builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates: ["ghcr.io/skirsten/proxy-to-host:{{ .Version }}"]
    dockerfile: Dockerfile

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
